apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-kubernetes-component
  annotations:
    backstage.io/kubernetes-id: standard-eks  
spec:
  lifecycle: production
  owner: guests
  type: service
