apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: argocd-component
  annotations:
    backstage.io/kubernetes-id: kubernetes-component 
    backstage.io/techdocs-ref: url:https://github.com/jwhong-3004/backstage-test
    github.com/project-slug: jwhong-3004/backstage-test
    argocd/proxy-url: '/argocd/api'
    argocd/app-name: test
    prometheus.io/rule: cpuUsage|component,container_cpu_usage_seconds_total{container_name="ubuntu",pod_name="application-77848cdb44-nk9d5"}
spec:
  lifecycle: production
  owner: guests
  type: service
