apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: argocd-component
  annotations:
    backstage.io/kubernetes-id: kubernetes-component 
    backstage.io/techdocs-ref: url:https://github.com/jwhong-3004/backstage-test
    github.com/project-slug: jwhong-3004/backstage-test
    argocd/proxy-url: '/argocd/api'
    argocd/app-name: test
    prometheus.io/rule: containerCPUUsage|pod_name,container_name,sum by (pod_name, container_name) (container_cpu_usage_seconds_total)
spec:
  lifecycle: production
  owner: guests
  type: service
