apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-kubernetes-component
  annotations:
    backstage.io/kubernetes-id: my-kubernetes-component 
    backstage.io/techdocs-ref: url:https://github.com/jwhong-3004/backstage-test/tree/main
    github.com/project-slug: jwhong3004/backstage-ec2
spec:
  lifecycle: production
  owner: guests
  type: service
