apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-kubernetes-component
  annotations:
    backstage.io/kubernetes-id: my-kubernetes-component 
  links:
    - title: Website
      url: http://backstage.io
    - title: Documentation
      url: https://backstage.io/docs  
  annotations:
    backstage.io/techdocs-ref: dir:.      
spec:
  lifecycle: production
  owner: guests
  type: service
