apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-kubernetes-component
  annotations:
    backstage.io/kubernetes-id: my-kubernetes-component 
    backstage.io/techdocs-ref: url:https://github.com/backstage/backstage/tree/master
spec:
  lifecycle: production
  owner: guests
  type: service
